[package]
name = "brain"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
rand_distr = "0.5.0"
rulinalg = "0.4.2"

gym-rs = { version = "0.3.0", optional = true }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = { version = "1.0.139", features = ["preserve_order"] }

[features]
gym = ["gym-rs"]

[[example]]
name = "xor"

[[example]]
name = "cart-pole"
required-features = ["gym"]

[dev-dependencies]
criterion = "0.5.1"
flamegraph = "0.6.7"

[[bench]]
name = "ctrnn"
harness = false

[[bench]]
name = "genome-mutate-bisection"
harness = false

[[bench]]
name = "genome-mutate-connection"
harness = false
