[package]
name = "brain"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
rand_distr = "0.5.0"
rulinalg = "0.4.2"

serde = { version = "1.0.218", features = ["derive"] }
serde_json = { version = "1.0.139", features = ["preserve_order"] }
fxhash = "0.2.1"

[features]
smol_bench = []

[[example]]
name = "xor"

[dev-dependencies]
criterion = "0.5.1"
flamegraph = "0.6.7"

[[bench]]
name = "ctrnn"
harness = false

[[bench]]
name = "avg-weight-diff"
harness = false

[[bench]]
name = "disjoint-excess-count"
harness = false

[[bench]]
name = "crossover-eq"
harness = false

[[bench]]
name = "crossover-ne"
harness = false

[[bench]]
name = "mutate-bisection"
harness = false

[[bench]]
name = "mutate-connection"
harness = false

[[bench]]
name = "speciate"
harness = false

[[bench]]
name = "innogen"
harness = false
