[package]
name = "brain"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
rand_distr = "0.5.0"
rulinalg = "0.4.2"

gym-rs = { version = "0.3.0", optional = true }

[features]
gym = ["gym-rs"]

[[example]]
name = "xor"

[[example]]
name = "cart-pole"
required-features = ["gym"]
